config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  get "auth/google_oauth2/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")

  delete "logout", to: "sessions#destroy", as: "logout"

  get "search", to: "search#new"
  post "search", to: "search#questions"

  resources :questions, only: [:index, :create, :new, :show] do
    resources :answers, only: [:create, :new]
  end

  root to: "questions#index"
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :question_id, presence: true
  validates :user_id, presence: true
  validates :body, length: { in: 3..65535 }
  validates :title, length: { in: 3..255 }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include PgSearch::Model

  ALLOWED_SEARCH_FIELDS = %i(body title).freeze

  # documentation: https://github.com/Casecommons/pg_search
  # some commented out lines have been left in here, as this are features I would love to add next
  pg_search_scope :search_for, lambda { |fields, query, find_any|
    raise ArgumentError, "Array expected, 'fields' was: #{fields}" unless fields.is_a?(Array)
    raise ArgumentError, "String expected, 'query' was: #{query}" unless query.is_a?(String)
    raise ArgumentError, "query too short, min 3 characters expected" unless query.length >= 3
    raise ArgumentError, "query too long, max 100 characters allowed" unless query.length <= 100

    allowed_fields = fields.select { |field| ALLOWED_SEARCH_FIELDS.include?(field) }
    raise ArgumentError, "Expected 'fields' to contain at least one of #{ALLOWED_SEARCH_FIELDS}" if allowed_fields.empty?

    {
      against: allowed_fields,
      query:,
      # ignoring: :accents, # needs migration to enable_extension 'unaccent'
      using: {
        tsearch: {
          any_word: !!find_any,
          # negation: true,        # this seems to be incompatible with :any_word or dictionary: "english"
          # dictionary: "english", # this would allow for stemming, but does not allow to find terms like "why"
          # tsvector_column: fields.map { |field| "#{field}_tsvector" }, # config.active_record.schema_format = :sql
        },
      },
    }
  }

  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :user_id, presence: true
  validates :body, length: { in: 3..65535 }
  validates :title, length: { in: 3..255 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :answers, dependent: :nullify
  has_many :questions, dependent: :nullify

  validates :email, presence: true
  validates :name, presence: true
  validates :provider, presence: true
  validates :provider_uid, presence: true

  def self.find_or_create_from(auth)
    where(provider: auth[:provider], provider_uid: auth[:uid]).first_or_initialize.tap do |user|
      user.email        = auth.dig(:info, :email)
      user.name         = auth.dig(:info, :name)
      user.image        = auth.dig(:info, :image)
      user.provider     = auth[:provider]
      user.provider_uid = auth[:uid]

      user.save!
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params.merge(user_id: current_user.id, question_id: params[:question_id]))

    if @answer.save
      flash[:notice] = "Answer was successfully created."
      redirect_to question_path(params[:question_id])
    else
      flash[:alert] = "Error: Answer not created."
      @question = Question.find(params[:question_id])
      render :new
    end
  end

  def new
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def authenticate
    redirect_to :login if current_user.blank?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))

    if @question.save
      flash[:notice] = "Question was successfully created."
      redirect_to "/questions#index"
    else
      flash[:alert] = "Error: Question not created."
      render :new
    end
  end

  def index
    @questions = Question.all.order(created_at: :desc) # TODO: add limit / pagination
  end

  def new
    @question = Question.new(user_id: current_user.id)
  end

  def show
    @question = Question.where(id: params[:id]).includes(:answers).first
    @answer = Answer.new(user_id: current_user.id, question_id: @question.id)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def new
    @find_any = true
  end

  def questions
    @questions = Question.search_for(fields, query, find_any)

    if @questions.empty?
      flash.now[:alert] = "No search results for query: #{question_params[:query]}"
      render :new
    else
      @search_result = true
      flash.now[:notice] = "Your search results"
      render "/questions/index"
    end
  rescue ArgumentError => e
    flash.now[:alert] = "Error: #{e.message}"
    render :new
  end

  private

  def fields
    fields = question_params.to_h.select { |k, v| Question::ALLOWED_SEARCH_FIELDS.include?(k.to_sym) && v.to_s == "1" }
    fields.keys.map(&:to_sym)
  end

  def find_any
    @find_any ||= question_params[:find_any_word] == "1"
  end

  def query
    @query ||= question_params[:query]
  end

  def question_params
    params.permit(:body, :title, :find_any_word, :query, :questions)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from(request.env["omniauth.auth"])
    session[:user_id] = user.id

    redirect_to root_path # TODO: redirect to last page
  end

  def destroy
    session.clear

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/redcarpet_helper.rb
# frozen_string_literal: true

# Documentation: https://github.com/vmg/redcarpet
module RedcarpetHelper
  def render_as_markdown(string)
    markdown.render(string).html_safe
  end

  def markdown
    @markdown ||= Redcarpet::Markdown.new(renderer, {
      autolink: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      highlight: true,
      no_intra_emphasis: true,
      space_after_headers: true,
      strikethrough: true,
    })
  end

  def renderer
    @renderer ||= RougeHelper::HTMLRenderWithCodeHighlighting.new(
      {
        escape_html: true,
        prettify: true,
        safe_links_only: true,
      }
    )
  end
end

app/helpers/rouge_helper.rb
# frozen_string_literal: true

module RougeHelper
  require "redcarpet"
  require "rouge"
  require "rouge/plugins/redcarpet"

  class HTMLRenderWithCodeHighlighting < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end
end

app/views/answers/_form.html.haml
= form_with model: [@question, @answer], local: true do |f|
  = render partial: "/layouts/errors", locals: { record: @answer }

  .field
    .label Title
    = f.text_field :title, placeholder: "Brief answer", maxlength: 255

  .field
    .label Body
    = f.text_area :body, placeholder: "tl;dr answer, markdown enabled", maxlength: 65535

  .field.actions
    = f.submit "Answer"

app/views/answers/new.html.haml
%h2 Give an answer

= render partial: "form"

app/views/layouts/_errors.html.haml
- if record.errors.any?
  #error_explanation.failure
    %h3= "#{pluralize(record.errors.count, "error")} prohibited this #{record.class.name} from being saved:"
    %ul
      - record.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for(:title) || "QandA"
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}
    %meta{name: "mobile-web-app-capable", content: "yes"}
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    %link{rel: "icon", href: "/icon.png", type: "image/png"}
    %link{rel: "icon", href: "/icon.svg", type: "image/svg+xml"}
    %link{rel: "apple-touch-icon", href: "/icon.png"}

    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    %header
      - if current_user
        %b= "Hello #{current_user.name}"
        |
        = link_to "Logout", logout_path, method: :delete
        |
        = link_to "Questions", questions_path
        |
        = link_to "Ask Question", new_question_path
        |
        = link_to "Search", search_path
      - else
        = button_to "Please login with Google to continue", "/auth/google_oauth2", method: :post

      %hr

    %main
      - if current_user
        = yield

    %footer
      %hr

      - if flash[:notice]
        .success
          = flash[:notice]

      - if flash[:alert]
        .failure
          = flash[:alert]

app/views/questions/index.html.haml
- unless @search_result
  %h2 List of all questions

.questions
  - @questions.each do |question|
    .question
      .q-title= link_to question.title, question_path(question)
      .username= question.user.name
      .q-body.limited= render_as_markdown(question.body)

app/views/questions/new.html.haml
%h2 Ask a question

= form_with model: @question, local: true do |f|
  = render partial: "/layouts/errors", locals: { record: @question }

  .field
    .label Title
    = f.text_field :title, placeholder: "Brief question", maxlength: 255

  .field
    .label Body
    = f.text_area :body, placeholder: "All glorious details of your question, feel free to use markdown", maxlength: 65535

  .field.actions
    = f.submit "Submit"

app/views/questions/show.html.haml
.question
  .q-title= @question.title
  .username= @question.user.name
  .q-body= render_as_markdown(@question.body)

= render partial: "/answers/form"

.answers
  - @question.answers.to_a.each do |answer|

    .answer
      .a-title= answer.title
      .username= answer.user.name
      .a-body= render_as_markdown(answer.body)

app/views/search/_form.html.haml
= form_with url: search_path, method: :post, local: true do |f|
  .field
    .label.inline Search in titles:
    = f.check_box :search_in_titles, name: :title, checked: true

  .field
    .label.inline Search in bodies:
    = f.check_box :search_in_bodies, name: :body, checked: true

  .field
    .label.inline Any word can match:
    = f.check_box :find_any_word, checked: @find_any

  .field
    = f.text_field :query, value: @query, maxlength: 100
    = f.submit "Search"

app/views/search/new.html.haml
%h2 Search in questions

= render partial: "form"